# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1
    - CONFIG=osx_r_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "2yrCqAiyrkPyhCcvGENAmVJr6zyvNqtfxGFPjV3cVFA3Sf0N9yErvm4gmFu4bas2hIl+Fc3PAde9DyTzhdaMWVntp3tizkc+MjnZ+Uk6PNLIYGsolYZRBvF49TF6oRhAn1Mi9poeELKgx7lDbwUoZIjKQDlzQJ2y20Snt5vtXrdnFqvqTyPHopQao+4L7hqaD6BXQp7di1N+7B3/4k6dQaeUdFDxXf1bAVb49LxFGG81Kn5SfxN0NMlYhgjHotua6yS9IOg3lqh+6QbLuO1k3M0lFHp+ZwEAJAYtYEVBYJbiBJyLiArPp4u2OQ4ohtrEiBjTLNkOYTGxeCqEn5QzUoZBLSgDEM1Rq/kbhh892As5Irov87MbkViiLCzGGS7YkJA9KEms0BqlmP6aAe+q+n6WgkbSpNLj/3CowOmjpR3Wf0RaFNPnvOBtHgcpEL1VUtjumdUtWygKLBXsBG/zu9f54O1o9G5wfRNf1CW8YILMx06drC3nIJ/zBSczx9l4CLh2tEekGIl6IFpUM9RLzHa47S61gODLWvDwInCVIFebxMIVSU29O1Z/5A58X4ZMXca0BPajrw85M0jr/SzxZfidyoWJ/lB3DAYkhfVzoXtLpEP1U4K2kYd9sJm/11Hd/VCqm0G20f63xww1/YY9jvCoXZ4ULO5cuyxYgynVAiI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
