travis:
  secure:
    BINSTAR_TOKEN: YgMNa+9bBQwl5WuTW4QwTI2XcQy8Xs2S7AFH0PVO3dZ4ZlfvL+GcqqH0JSkwF+C8C3L0nZ9JCXGiJiPxexF1p5KaowU5YNaJW90x4EcASRaPNCaRgQiv9pSQwLnZ1tXc+MHvVmsxs+rOwVBWP4UFShmvJgIOgzODSvwlmI31xORdW+xSYKIkLtqa9zoF/IxQMf7tWR6xGlgWB7mH/nm9Dqt1Jf+s7OLSDXc3nsHjXmKDg0ZfwsXGEQvbua9UqTyHurHzTX9t8UhERqZIxYWA91DegWueSmInMz/Go9TU9A3UsaHQ+DTwQljoVN2wykJnrxNVOQx8cBs/kh5JYJRjL6Iu1QFNnloFIZsun8SKqvG1tIHHmO3Vfm5D8Zbfj30pJw+WHuQ9oYkgKqRF1HwYn8Lc8wJVo85Re21hUHHdhoiiHzjnT3AuEX2iCWpjVavD6M0o2+jTXIDHV+xXNA3UHZLyebms+3550OaFYIF82vevsqfCjX4LbFwpC+f0xzhcS+CPeNtTdhTXDWYhVU4qRE5VU3yA1rbiK3aagPj7aZIGf4aWaTZVpEysycGW8Xz9+aCH0IdiWW2ACXnetkysVFah/Eym+BlK8CuOqasscyXrjtNn3d48e2/yktrZKJ1syj+cwcJTe3soxakarl2nRz/XdcjOiafN8s1euRDuWXc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
