travis:
  secure:
    BINSTAR_TOKEN: 2yrCqAiyrkPyhCcvGENAmVJr6zyvNqtfxGFPjV3cVFA3Sf0N9yErvm4gmFu4bas2hIl+Fc3PAde9DyTzhdaMWVntp3tizkc+MjnZ+Uk6PNLIYGsolYZRBvF49TF6oRhAn1Mi9poeELKgx7lDbwUoZIjKQDlzQJ2y20Snt5vtXrdnFqvqTyPHopQao+4L7hqaD6BXQp7di1N+7B3/4k6dQaeUdFDxXf1bAVb49LxFGG81Kn5SfxN0NMlYhgjHotua6yS9IOg3lqh+6QbLuO1k3M0lFHp+ZwEAJAYtYEVBYJbiBJyLiArPp4u2OQ4ohtrEiBjTLNkOYTGxeCqEn5QzUoZBLSgDEM1Rq/kbhh892As5Irov87MbkViiLCzGGS7YkJA9KEms0BqlmP6aAe+q+n6WgkbSpNLj/3CowOmjpR3Wf0RaFNPnvOBtHgcpEL1VUtjumdUtWygKLBXsBG/zu9f54O1o9G5wfRNf1CW8YILMx06drC3nIJ/zBSczx9l4CLh2tEekGIl6IFpUM9RLzHa47S61gODLWvDwInCVIFebxMIVSU29O1Z/5A58X4ZMXca0BPajrw85M0jr/SzxZfidyoWJ/lB3DAYkhfVzoXtLpEP1U4K2kYd9sJm/11Hd/VCqm0G20f63xww1/YY9jvCoXZ4ULO5cuyxYgynVAiI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
