travis:
  secure:
    BINSTAR_TOKEN: Lkt9rKYw/DVopv68rK+PZJqbzJNzcv+qvN+LG6yuEf/CBpBsytE7yXvsm0v9Vn3MLwIrQG1n1zUylOyeW73IXNYEjv5z5EDqWJ75aWBngy14JF4wwC/h6fo0adGtkpdpv0df7nQeajZ+yzWm9byt7j6S23VUPzpkrHsZFpcV1LQtC6+ElGMOtjE0Pj4z1gslhwWlq8jO38gMvbGmWE+OPPkQ+A/wEc0XCW52PAwAq6So23HZzo4WTdx3zAntESMoYJ9y9YTonWuQ1jdxfdSejWqxBBK3j1w3i6WHS0Efcgyx/KRUTYEzyJI8Qxfs/Nok6tgSOsS10/KE0RczRitUDDn6NGTRu2wQCIBAVnJnUxrrjsEh1ru342PigmStaxfE4ZpdRYylcE0Hh6FPVqOxYd4whROy/Vl8LCwI3nhNdiROf5N4gv7wkfSVYr0mZX6hH5r8DMRgPCYTi3MAbf2YUvIQ2Kjzkk4cY+nwhJ9hPsDzG10nY+oeEoADY2L6a77wQIzklSl3AwfhuZnqf0gw66SthFw5cw3a3+v7ajI7aJN+E4zaAvI2CSWFR5r7J2ZANNgBY5+l4doZz1DSDq229QbN3f63gULRGzidX1gTwQgkCxBw1deUcSligpw7244tiIrj2wHdL7pQ22htA1wXwQ/onhfTBGXFDZFDQLcNf3Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
